// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/http;

public type ToolCall record {
    string id = "null";
    ToolTypes 'type = "function";
    FunctionCall 'function;
};

public type ChatCompletionChoice record {
    int index;
    AssistantMessage message;
    "stop"|"length"|"model_length"|"error"|"tool_calls" finish_reason;
};

public type LegacyJobMetadataOut record {
    # The approximated time (in seconds) for the fine-tuning process to complete.
    anydata expected_duration_seconds?;
    # The cost of the fine-tuning job.
    anydata cost?;
    # The currency used for the fine-tuning job cost.
    anydata cost_currency?;
    # The number of tokens consumed by one training step.
    anydata train_tokens_per_step?;
    # The total number of tokens used during the fine-tuning process.
    anydata train_tokens?;
    # The total number of tokens in the training dataset.
    anydata data_tokens?;
    anydata estimated_start_time?;
    boolean deprecated = true;
    string details;
    # The number of complete passes through the entire training dataset.
    anydata epochs?;
    # The number of training steps to perform. A training step refers to a single update of the model weights during the fine-tuning process. This update is typically calculated using a batch of samples from the training dataset.
    anydata training_steps?;
    "job.metadata" 'object = "job.metadata";
};

# this restriction of `Function` is used to select a specific function to call
public type FunctionName record {
    string name;
};

public type DeleteFileOut record {
    # The ID of the deleted file.
    string id;
    # The object type that was deleted
    string 'object;
    # The deletion status.
    boolean deleted;
};

public type ArchiveFTModelOut record {
    string id;
    "model" 'object = "model";
    boolean archived = true;
};

public type RetrieveFileOut record {
    # The unique identifier of the file.
    string id;
    # The object type, which is always "file".
    string 'object;
    # The size of the file, in bytes.
    int bytes;
    # The UNIX timestamp (in seconds) of the event.
    int created_at;
    # The name of the uploaded file.
    string filename;
    # The intended purpose of the uploaded file. Only accepts fine-tuning (`fine-tune`) for now.
    "fine-tune" purpose;
    SampleType sample_type;
    anydata num_lines?;
    Source 'source;
};

public type GithubRepositoryIn record {
    "github" 'type = "github";
    string name;
    string owner;
    anydata ref?;
    decimal weight = 1;
    string token;
};

public type EventOut record {
    # The name of the event.
    string name;
    anydata data?;
    # The UNIX timestamp (in seconds) of the event.
    int created_at;
};

public type FileSchema record {
    # The unique identifier of the file.
    string id;
    # The object type, which is always "file".
    string 'object;
    # The size of the file, in bytes.
    int bytes;
    # The UNIX timestamp (in seconds) of the event.
    int created_at;
    # The name of the uploaded file.
    string filename;
    # The intended purpose of the uploaded file. Only accepts fine-tuning (`fine-tune`) for now.
    "fine-tune" purpose;
    SampleType sample_type;
    anydata num_lines?;
    Source 'source;
};

# The fine-tuning hyperparameter settings used in a fine-tune job.
public type TrainingParametersIn record {
    # The number of training steps to perform. A training step refers to a single update of the model weights during the fine-tuning process. This update is typically calculated using a batch of samples from the training dataset.
    anydata training_steps?;
    # A parameter describing how much to adjust the pre-trained model's weights in response to the estimated error each time the weights are updated during the fine-tuning process.
    @constraint:Number {minValue: 1.0E-8, maxValue: 1}
    decimal learning_rate = 1.0E-4;
    # (Advanced Usage) Weight decay adds a term to the loss function that is proportional to the sum of the squared weights. This term reduces the magnitude of the weights and prevents them from growing too large.
    anydata weight_decay = 0.1;
    # (Advanced Usage) A parameter that specifies the percentage of the total training steps at which the learning rate warm-up phase ends. During this phase, the learning rate gradually increases from a small value to the initial learning rate, helping to stabilize the training process and improve convergence. Similar to `pct_start` in [mistral-finetune](https://github.com/mistralai/mistral-finetune)
    anydata warmup_fraction = 0.05;
    anydata epochs?;
    anydata fim_ratio = 0.9;
};

public type ToolMessage record {
    string content;
    anydata tool_call_id?;
    anydata name?;
    "tool" role = "tool";
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
|};

public type Tool record {
    ToolTypes 'type = "function";
    Function 'function;
};

# Extra fields for fine-tuned models.
public type FTModelCard record {
    string id;
    string 'object = "model";
    int created?;
    string owned_by = "mistralai";
    anydata name?;
    anydata description?;
    int max_context_length = 32768;
    string[] aliases = [];
    anydata deprecation?;
    ModelCapabilities capabilities;
    anydata 'type = "fine-tuned";
    string job;
    string root;
    boolean archived = false;
};

public type ResponseFormat record {
    ResponseFormats 'type = "text";
};

public type FTModelCapabilitiesOut record {
    boolean completion_chat = true;
    boolean completion_fim = false;
    boolean function_calling = false;
    boolean fine_tuning = false;
};

public type UnarchiveFTModelOut record {
    string id;
    "model" 'object = "model";
    boolean archived = false;
};

public type AssistantMessage record {
    anydata content?;
    anydata tool_calls?;
    # Set this to `true` when adding an assistant message as prefix to condition the model response. The role of the prefix message is to force the model to start its answer by the content of the message.
    boolean prefix = false;
    "assistant" role = "assistant";
};

public type GithubRepositoryOut record {
    "github" 'type = "github";
    string name;
    string owner;
    anydata ref?;
    @constraint:Number {minValueExclusive: 0}
    decimal weight = 1;
    @constraint:String {maxLength: 40, minLength: 40}
    string commit_id;
};

public type ImageURL record {
    string url;
    anydata detail?;
};

public type TextChunk record {
    "text" 'type = "text";
    string text;
};

public type ModelCapabilities record {
    boolean completion_chat = true;
    boolean completion_fim = false;
    boolean function_calling = true;
    boolean fine_tuning = false;
    boolean vision = false;
};

public type WandbIntegrationOut record {
    "wandb" 'type = "wandb";
    # The name of the project that the new run will be created under.
    string project;
    # A display name to set for the run. If not set, will use the job ID as the name.
    anydata name?;
    anydata run_name?;
};

public type ChatCompletionResponse record {
    *ChatCompletionResponseBase;
    ChatCompletionChoice[] choices?;
};

public type EmbeddingResponseData record {
    string 'object?;
    decimal[] embedding?;
    int index?;
};

public type TrainingFile record {
    string file_id;
    decimal weight = 1;
};

public type FTModelOut record {
    string id;
    "model" 'object = "model";
    int created;
    string owned_by;
    string root;
    boolean archived;
    anydata name?;
    anydata description?;
    FTModelCapabilitiesOut capabilities;
    int max_context_length = 32768;
    string[] aliases = [];
    string job;
};

public type ListFilesOut record {
    FileSchema[] data;
    string 'object;
};

public type ToolTypes "function";

# ToolChoice is either a ToolChoiceEnum or a ToolChoice
public type ToolChoice record {
    ToolTypes 'type = "function";
    FunctionName 'function;
};

# The name of the model to fine-tune.
public type FineTuneableModel "open-mistral-7b"|"mistral-small-latest"|"codestral-latest"|"mistral-large-latest"|"open-mistral-nemo";

public type BaseModelCard record {
    string id;
    string 'object = "model";
    int created?;
    string owned_by = "mistralai";
    anydata name?;
    anydata description?;
    int max_context_length = 32768;
    string[] aliases = [];
    anydata deprecation?;
    ModelCapabilities capabilities;
    anydata 'type = "base";
};

public type WandbIntegration record {
    "wandb" 'type = "wandb";
    # The name of the project that the new run will be created under.
    string project;
    # A display name to set for the run. If not set, will use the job ID as the name.
    anydata name?;
    # The WandB API key to use for authentication.
    @constraint:String {maxLength: 40, minLength: 40}
    string api_key;
    anydata run_name?;
};

# An object specifying the format that the model must output. Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is in JSON. When using JSON mode you MUST also instruct the model to produce JSON yourself with a system or a user message.
public type ResponseFormats "text"|"json_object";

public type FIMCompletionRequest record {
    # ID of the model to use. Only compatible for now with:
    #   - `codestral-2405`
    #   - `codestral-latest`
    anydata model;
    # What sampling temperature to use, between 0.0 and 1.0. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both.
    @constraint:Number {minValue: 0, maxValue: 1.5}
    decimal temperature = 0.7;
    # Nucleus sampling, where the model considers the results of the tokens with `top_p` probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both.
    @constraint:Number {minValue: 0, maxValue: 1}
    decimal top_p = 1;
    # The maximum number of tokens to generate in the completion. The token count of your prompt plus `max_tokens` cannot exceed the model's context length.
    anydata max_tokens?;
    # The minimum number of tokens to generate in the completion.
    anydata min_tokens?;
    # Whether to stream back partial progress. If set, tokens will be sent as data-only server-side events as they become available, with the stream terminated by a data: [DONE] message. Otherwise, the server will hold the request open until the timeout or until completion, with the response containing the full result as JSON.
    boolean 'stream = false;
    # Stop generation if this token is detected. Or if one of these tokens is detected when providing an array
    string|string[] stop?;
    # The seed to use for random sampling. If set, different calls will generate deterministic results.
    anydata random_seed?;
    # The text/code to complete.
    string prompt;
    # Optional text/code that adds more context for the model. When given a `prompt` and a `suffix` the model will fill what is between them. When `suffix` is not provided, the model will simply execute completion starting with `prompt`.
    anydata suffix = null;
};

public type SystemMessage record {
    string|TextChunk[] content;
    "system" role = "system";
};

# Represents the Queries record for the operation: jobs_api_routes_fine_tuning_create_fine_tuning_job
public type Jobs_api_routes_fine_tuning_create_fine_tuning_jobQueries record {
    # * If `true` the job is not spawned, instead the query returns a handful of useful metadata
    #   for the user to perform sanity checks (see `LegacyJobMetadataOut` response).
    # * Otherwise, the job is started and the query returns the job ID along with some of the
    #   input parameters (see `JobOut` response).
    anydata dry_run?;
};

public type ContentChunk TextChunk|ImageURLChunk;

public type MultiPartBodyParams record {
    "fine-tune" purpose = "fine-tune";
    # The File object (not file name) to be uploaded.
    #  To upload a file and specify a custom file name you should format your request as such:
    #  ```bash
    #  file=@path/to/your/file.jsonl;filename=custom_name.jsonl
    #  ```
    #  Otherwise, you can just keep the original file name:
    #  ```bash
    #  file=@path/to/your/file.jsonl
    #  ```
    record {byte[] fileContent; string fileName;} file;
};

public type AgentsCompletionRequest record {
    # The maximum number of tokens to generate in the completion. The token count of your prompt plus `max_tokens` cannot exceed the model's context length.
    anydata max_tokens?;
    # Whether to stream back partial progress. If set, tokens will be sent as data-only server-side events as they become available, with the stream terminated by a data: [DONE] message. Otherwise, the server will hold the request open until the timeout or until completion, with the response containing the full result as JSON.
    boolean 'stream = false;
    # Stop generation if this token is detected. Or if one of these tokens is detected when providing an array
    string|string[] stop?;
    # The seed to use for random sampling. If set, different calls will generate deterministic results.
    anydata random_seed?;
    # The prompt(s) to generate completions for, encoded as a list of dict with role and content.
    (UserMessage|AssistantMessage|ToolMessage)[] messages;
    ResponseFormat response_format?;
    anydata tools?;
    ToolChoice|ToolChoiceEnum tool_choice = "auto";
    # The ID of the agent to use for this completion.
    string agent_id;
};

public type ChatCompletionResponseBase record {
    *ResponseBase;
    int created?;
};

public type JobMetadataOut record {
    anydata expected_duration_seconds?;
    anydata cost?;
    anydata cost_currency?;
    anydata train_tokens_per_step?;
    anydata train_tokens?;
    anydata data_tokens?;
    anydata estimated_start_time?;
};

public type UserMessage record {
    string|ContentChunk[] content;
    "user" role = "user";
};

public type Source "upload"|"repository";

public type FIMCompletionResponse record {
    *ChatCompletionResponse;
    string model?;
};

public type ChatCompletionRequest record {
    # ID of the model to use. You can use the [List Available Models](/api/#tag/models/operation/list_models_v1_models_get) API to see all of your available models, or see our [Model overview](/models) for model descriptions.
    anydata model;
    # What sampling temperature to use, we recommend between 0.0 and 1.0. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both.
    @constraint:Number {minValue: 0, maxValue: 1.5}
    decimal temperature = 0.3;
    # Nucleus sampling, where the model considers the results of the tokens with `top_p` probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both.
    @constraint:Number {minValue: 0, maxValue: 1}
    decimal top_p = 1;
    # The maximum number of tokens to generate in the completion. The token count of your prompt plus `max_tokens` cannot exceed the model's context length.
    anydata max_tokens?;
    # Whether to stream back partial progress. If set, tokens will be sent as data-only server-side events as they become available, with the stream terminated by a data: [DONE] message. Otherwise, the server will hold the request open until the timeout or until completion, with the response containing the full result as JSON.
    boolean 'stream = false;
    # Stop generation if this token is detected. Or if one of these tokens is detected when providing an array
    string|string[] stop?;
    # The seed to use for random sampling. If set, different calls will generate deterministic results.
    anydata random_seed?;
    # The prompt(s) to generate completions for, encoded as a list of dict with role and content.
    (SystemMessage|UserMessage|AssistantMessage|ToolMessage)[] messages;
    ResponseFormat response_format?;
    anydata tools?;
    ToolChoice|ToolChoiceEnum tool_choice = "auto";
    # Whether to inject a safety prompt before all conversations.
    boolean safe_prompt = false;
};

# {"type":"image_url","image_url":{"url":"data:image/png;base64,iVBORw0
public type ImageURLChunk record {
    "image_url" 'type = "image_url";
    ImageURL|string image_url;
};

public type Function record {
    string name;
    string description = "";
    record {} parameters;
};

public type ModelList record {
    string 'object = "list";
    (BaseModelCard|FTModelCard)[] data?;
};

public type DeleteModelOut record {
    # The ID of the deleted model.
    string id;
    # The object type that was deleted
    string 'object = "model";
    # The deletion status
    boolean deleted = true;
};

public type ToolChoiceEnum "auto"|"none"|"any"|"required";

public type TrainingParameters record {
    anydata training_steps?;
    @constraint:Number {minValue: 1.0E-8, maxValue: 1}
    decimal learning_rate = 1.0E-4;
    anydata weight_decay = 0.1;
    anydata warmup_fraction = 0.05;
    anydata epochs?;
    anydata fim_ratio = 0.9;
};

public type DetailedJobOut record {
    string id;
    boolean auto_start;
    TrainingParameters hyperparameters;
    FineTuneableModel model;
    "QUEUED"|"STARTED"|"VALIDATING"|"VALIDATED"|"RUNNING"|"FAILED_VALIDATION"|"FAILED"|"SUCCESS"|"CANCELLED"|"CANCELLATION_REQUESTED" status;
    string job_type;
    int created_at;
    int modified_at;
    string[] training_files;
    anydata validation_files = [];
    "job" 'object = "job";
    anydata fine_tuned_model?;
    anydata suffix?;
    anydata integrations?;
    anydata trained_tokens?;
    @constraint:Array {maxLength: 20}
    (GithubRepositoryOut)[] repositories = [];
    anydata metadata?;
    # Event items are created every time the status of a fine-tuning job changes. The timestamped list of all events is accessible here.
    EventOut[] events = [];
    CheckpointOut[] checkpoints = [];
};

public type ResponseBase record {
    string id?;
    string 'object?;
    string model?;
    UsageInfo usage?;
};

public type UpdateFTModelIn record {
    anydata name?;
    anydata description?;
};

public type FunctionCall record {
    string name;
    record {}|string arguments;
};

public type UsageInfo record {
    int prompt_tokens;
    int completion_tokens;
    int total_tokens;
};

public type JobOut record {
    # The ID of the job.
    string id;
    boolean auto_start;
    TrainingParameters hyperparameters;
    FineTuneableModel model;
    # The current status of the fine-tuning job.
    "QUEUED"|"STARTED"|"VALIDATING"|"VALIDATED"|"RUNNING"|"FAILED_VALIDATION"|"FAILED"|"SUCCESS"|"CANCELLED"|"CANCELLATION_REQUESTED" status;
    # The type of job (`FT` for fine-tuning).
    string job_type;
    # The UNIX timestamp (in seconds) for when the fine-tuning job was created.
    int created_at;
    # The UNIX timestamp (in seconds) for when the fine-tuning job was last modified.
    int modified_at;
    # A list containing the IDs of uploaded files that contain training data.
    string[] training_files;
    # A list containing the IDs of uploaded files that contain validation data.
    anydata validation_files = [];
    # The object type of the fine-tuning job.
    "job" 'object = "job";
    # The name of the fine-tuned model that is being created. The value will be `null` if the fine-tuning job is still running.
    anydata fine_tuned_model?;
    # Optional text/code that adds more context for the model. When given a `prompt` and a `suffix` the model will fill what is between them. When `suffix` is not provided, the model will simply execute completion starting with `prompt`.
    anydata suffix?;
    # A list of integrations enabled for your fine-tuning job.
    anydata integrations?;
    # Total number of tokens trained.
    anydata trained_tokens?;
    @constraint:Array {maxLength: 20}
    (GithubRepositoryOut)[] repositories = [];
    anydata metadata?;
};

# Metrics at the step number during the fine-tuning job. Use these metrics to assess if the training is going smoothly (loss should decrease, token accuracy should increase).
public type MetricOut record {
    anydata train_loss?;
    anydata valid_loss?;
    anydata valid_mean_token_accuracy?;
};

public type UploadFileOut record {
    # The unique identifier of the file.
    string id;
    # The object type, which is always "file".
    string 'object;
    # The size of the file, in bytes.
    int bytes;
    # The UNIX timestamp (in seconds) of the event.
    int created_at;
    # The name of the uploaded file.
    string filename;
    # The intended purpose of the uploaded file. Only accepts fine-tuning (`fine-tune`) for now.
    "fine-tune" purpose;
    SampleType sample_type;
    anydata num_lines?;
    Source 'source;
};

public type JobIn record {
    FineTuneableModel model;
    TrainingFile[] training_files = [];
    # A list containing the IDs of uploaded files that contain validation data. If you provide these files, the data is used to generate validation metrics periodically during fine-tuning. These metrics can be viewed in `checkpoints` when getting the status of a running fine-tuning job. The same data should not be present in both train and validation files.
    anydata validation_files?;
    TrainingParametersIn hyperparameters;
    # A string that will be added to your fine-tuning model name. For example, a suffix of "my-great-model" would produce a model name like `ft:open-mistral-7b:my-great-model:xxx...`
    anydata suffix?;
    # A list of integrations to enable for your fine-tuning job.
    anydata integrations?;
    (GithubRepositoryIn)[] repositories = [];
    # This field will be required in a future release.
    boolean auto_start?;
};

public type JobsOut record {
    JobOut[] data = [];
    "list" 'object = "list";
    int total;
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

# Represents the Queries record for the operation: jobs_api_routes_fine_tuning_get_fine_tuning_jobs
public type Jobs_api_routes_fine_tuning_get_fine_tuning_jobsQueries record {
    # The Weights and Biases project to filter on. When set, the other results are not displayed.
    anydata wandb_project?;
    # The Weight and Biases run name to filter on. When set, the other results are not displayed.
    anydata wandb_name?;
    # The date/time to filter on. When set, the results for previous creation times are not displayed.
    anydata created_after?;
    # The model name used for fine-tuning to filter on. When set, the other results are not displayed.
    anydata model?;
    # The page number of the results to be returned.
    int page = 0;
    # The model suffix to filter on. When set, the other results are not displayed.
    anydata suffix?;
    # When set, only return results for jobs created by the API caller. Other results are not displayed.
    boolean created_by_me = false;
    # The number of items to return per page.
    int page_size = 100;
    # The current job state to filter on. When set, the other results are not displayed.
    anydata status?;
};

public type EmbeddingRequest record {
    # Text to embed.
    string|string[] input;
    # ID of the model to use.
    string model;
    # The format to return the embeddings in.
    anydata encoding_format = "float";
};

public type EmbeddingResponse record {
    *ResponseBase;
    EmbeddingResponseData[] data;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

public type SampleType "pretrain"|"instruct";

public type CheckpointOut record {
    MetricOut metrics;
    # The step number that the checkpoint was created at.
    int step_number;
    # The UNIX timestamp (in seconds) for when the checkpoint was created.
    int created_at;
};
